create table CONSTRAINT_CONFIG (
  ID bigint generated by default as identity (start with 1),
  NAME varchar(255) not null,
  AUTHOR varchar(255),
  MODIFIED timestamp not null,
  VERSION integer not null,
  primary key (ID)
);

create table VALIDATION_RULE (
  ID bigint generated by default as identity (start with 1),
  NAME varchar(255) not null,
  NULLABLE bit not null,
  REG_EXP varchar(255) not null,
  DESCRIPTION varchar(255),
  ORDER_IN_CONFIG integer not null,
  VERSION integer not null,
  CONFIG_ID bigint not null,
  primary key (ID)
);

create table OUTPUT_FILE (
  ID bigint generated by default as identity (start with 1),
  NAME varchar(255) not null,
  ORDER_IN_CONFIG integer not null,
  VERSION integer not null,
  PARENT_ID bigint,
  CONFIG_ID bigint not null,
  primary key (ID)
);

create table OUTPUT_FIELD (
  ID bigint generated by default as identity (start with 1),
  NAME varchar(255) not null,
  ORDER_IN_FILE integer not null,
  VERSION integer not null,
  FILE_ID bigint not null,
  RULE_ID bigint,
  primary key (ID)
);

alter table VALIDATION_RULE
  add constraint FK_VALIDATION_RULE_CONFIG_ID
  foreign key (CONFIG_ID)
  references CONSTRAINT_CONFIG
  on delete cascade;

alter table OUTPUT_FILE
  add constraint FK_OUTPUT_FILE_PARENT_ID
  foreign key (PARENT_ID)
  references OUTPUT_FILE
  on delete set null;

alter table OUTPUT_FILE
  add constraint FK_OUTPUT_FILE_CONFIG_ID
  foreign key (CONFIG_ID)
  references CONSTRAINT_CONFIG
  on delete cascade;

alter table OUTPUT_FIELD
  add constraint FK_OUTPUT_FIELD_FILE_ID
  foreign key (FILE_ID)
  references OUTPUT_FILE
  on delete cascade;

alter table OUTPUT_FIELD
  add constraint FK_OUTPUT_FIELD_RULE_ID
  foreign key (RULE_ID)
  references VALIDATION_RULE
  on delete set null;
