-- Table deleting
DROP TABLE IF EXISTS OUTPUT_FIELD;
DROP TABLE IF EXISTS OUTPUT_FILE;
DROP TABLE IF EXISTS VALIDATION_RULE;
DROP TABLE IF EXISTS CONSTRAINT_CONFIG;

-- Table creation: "CONSTRAINT_CONFIG"
CREATE TABLE CONSTRAINT_CONFIG (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  AUTHOR VARCHAR(255),
  MODIFIED TIMESTAMP NOT NULL,
  VERSION INTEGER NOT NULL
);

-- Table creation: "VALIDATION_RULE"
CREATE TABLE VALIDATION_RULE (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  NULLABLE BIT NOT NULL,
  REG_EXP VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(1000),
  ORDER_IN_CONFIG INTEGER NOT NULL,
  VERSION INTEGER NOT NULL,
  CONFIG_ID BIGINT NOT NULL,

  CONSTRAINT FK_VALIDATION_RULE_CONFIG_ID
    FOREIGN KEY (CONFIG_ID)
    REFERENCES CONSTRAINT_CONFIG (ID)
    ON DELETE CASCADE
);

-- Table creation: "OUTPUT_FILE"
CREATE TABLE OUTPUT_FILE (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  ORDER_IN_CONFIG INTEGER NOT NULL,
  VERSION INTEGER NOT NULL,
  PARENT_ID BIGINT,
  CONFIG_ID BIGINT NOT NULL,

  CONSTRAINT FK_OUTPUT_FILE_PARENT_ID
    FOREIGN KEY (PARENT_ID)
    REFERENCES OUTPUT_FILE (ID)
    ON DELETE SET NULL,
  CONSTRAINT FK_OUTPUT_FILE_CONFIG_ID
    FOREIGN KEY (CONFIG_ID)
    REFERENCES CONSTRAINT_CONFIG (ID)
    ON DELETE CASCADE
);

-- Table creation: "OUTPUT_FIELD"
CREATE TABLE OUTPUT_FIELD (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  ORDER_IN_FILE INTEGER NOT NULL,
  VERSION INTEGER NOT NULL,
  FILE_ID BIGINT NOT NULL,
  RULE_ID BIGINT,
  
  CONSTRAINT FK_OUTPUT_FIELD_FILE_ID
    FOREIGN KEY (FILE_ID)
    REFERENCES OUTPUT_FILE (ID)
    ON DELETE CASCADE,
  CONSTRAINT FK_OUTPUT_FIELD_RULE_ID
    FOREIGN KEY (RULE_ID)
    REFERENCES VALIDATION_RULE (ID)
    ON DELETE SET NULL
);
