-- Delete all data from tables
DELETE FROM OUTPUT_FIELD;
DELETE FROM OUTPUT_FILE;
DELETE FROM VALIDATION_RULE;
DELETE FROM CONSTRAINT_CONFIG;

-- Table populating: "CONSTRAINT_CONFIG"
INSERT INTO CONSTRAINT_CONFIG(NAME, AUTHOR, MODIFIED, VERSION)
    VALUES ('config-1', 'author-1', '2010-01-01 00:00:00', 0);
INSERT INTO CONSTRAINT_CONFIG(NAME, AUTHOR, MODIFIED, VERSION)
    VALUES ('config-2', 'author-2', '2011-01-01 00:00:00', 0);

-- Table populating: "VALIDATION_RULE"
INSERT INTO VALIDATION_RULE(NAME, NULLABLE, REG_EXP, DESCRIPTION, ORDER_IN_CONFIG, VERSION, CONFIG_ID)
    VALUES ('rule-1', true, 'regexp-1', null, 0, 0, 1);
INSERT INTO VALIDATION_RULE(NAME, NULLABLE, REG_EXP, DESCRIPTION, ORDER_IN_CONFIG, VERSION, CONFIG_ID)
    VALUES ('rule-2', false, 'regexp-2', null, 1, 0, 1);
INSERT INTO VALIDATION_RULE(NAME, NULLABLE, REG_EXP, DESCRIPTION, ORDER_IN_CONFIG, VERSION, CONFIG_ID)
    VALUES ('rule-3', true, 'regexp-3', null, 0, 0, 2);
INSERT INTO VALIDATION_RULE(NAME, NULLABLE, REG_EXP, DESCRIPTION, ORDER_IN_CONFIG, VERSION, CONFIG_ID)
    VALUES ('rule-4', false, 'regexp-4', null, 1, 0, 2);

-- Table populating: "OUTPUT_FILE"
INSERT INTO OUTPUT_FILE(NAME, ORDER_IN_CONFIG, VERSION, PARENT_ID, CONFIG_ID)
    VALUES ('file-1.csv', 0, 0, null, 1);
INSERT INTO OUTPUT_FILE(NAME, ORDER_IN_CONFIG, VERSION, PARENT_ID, CONFIG_ID)
    VALUES ('file-2.csv', 1, 0, null, 1);
INSERT INTO OUTPUT_FILE(NAME, ORDER_IN_CONFIG, VERSION, PARENT_ID, CONFIG_ID)
    VALUES ('file-3.csv', 2, 0, 1, 1);
INSERT INTO OUTPUT_FILE(NAME, ORDER_IN_CONFIG, VERSION, PARENT_ID, CONFIG_ID)
    VALUES ('file-4.csv', 3, 0, 1, 1);
INSERT INTO OUTPUT_FILE(NAME, ORDER_IN_CONFIG, VERSION, PARENT_ID, CONFIG_ID)
    VALUES ('file-5.csv', 0, 0, null, 2);
INSERT INTO OUTPUT_FILE(NAME, ORDER_IN_CONFIG, VERSION, PARENT_ID, CONFIG_ID)
    VALUES ('file-6.csv', 1, 0, 5, 2);
INSERT INTO OUTPUT_FILE(NAME, ORDER_IN_CONFIG, VERSION, PARENT_ID, CONFIG_ID)
    VALUES ('file-7.csv', 2, 0, null, 2);
INSERT INTO OUTPUT_FILE(NAME, ORDER_IN_CONFIG, VERSION, PARENT_ID, CONFIG_ID)
    VALUES ('file-8.csv', 3, 0, 7, 2);

-- Table populating: "OUTPUT_FIELD"
INSERT INTO OUTPUT_FIELD(NAME, ORDER_IN_FILE, VERSION, FILE_ID, RULE_ID)
    VALUES ('field-1', 0, 0, 1, 1);
INSERT INTO OUTPUT_FIELD(NAME, ORDER_IN_FILE, VERSION, FILE_ID, RULE_ID)
    VALUES ('field-2', 1, 0, 1, 2);
INSERT INTO OUTPUT_FIELD(NAME, ORDER_IN_FILE, VERSION, FILE_ID, RULE_ID)
    VALUES ('field-3', 0, 0, 2, null);
INSERT INTO OUTPUT_FIELD(NAME, ORDER_IN_FILE, VERSION, FILE_ID, RULE_ID)
    VALUES ('field-4', 1, 0, 2, 1);
INSERT INTO OUTPUT_FIELD(NAME, ORDER_IN_FILE, VERSION, FILE_ID, RULE_ID)
    VALUES ('field-5', 0, 0, 3, 2);
INSERT INTO OUTPUT_FIELD(NAME, ORDER_IN_FILE, VERSION, FILE_ID, RULE_ID)
    VALUES ('field-6', 1, 0, 3, null);
INSERT INTO OUTPUT_FIELD(NAME, ORDER_IN_FILE, VERSION, FILE_ID, RULE_ID)
    VALUES ('field-7', 0, 0, 5, 3);
INSERT INTO OUTPUT_FIELD(NAME, ORDER_IN_FILE, VERSION, FILE_ID, RULE_ID)
    VALUES ('field-8', 1, 0, 5, 4);
INSERT INTO OUTPUT_FIELD(NAME, ORDER_IN_FILE, VERSION, FILE_ID, RULE_ID)
    VALUES ('field-9', 0, 0, 7, null);
INSERT INTO OUTPUT_FIELD(NAME, ORDER_IN_FILE, VERSION, FILE_ID, RULE_ID)
    VALUES ('field-10', 1, 0, 7, 3);
INSERT INTO OUTPUT_FIELD(NAME, ORDER_IN_FILE, VERSION, FILE_ID, RULE_ID)
    VALUES ('field-11', 0, 0, 8, 4);
INSERT INTO OUTPUT_FIELD(NAME, ORDER_IN_FILE, VERSION, FILE_ID, RULE_ID)
    VALUES ('field-12', 1, 0, 8, null);
